edge_brush:
  pointCloudTopic: "/rslidar_points"
  lidarFrame: "rslidar_sim"
  cmdTopic: "nav/cmd_vel"
  targetDis: 0.65
  linearKp: 0.5
  angularKp: 0.01
  trimDlimit: [0, -1, -1, 0]
  trimUlimit: [1.3, 1, -0.3, 0]
  odomTopic: "odom_basefootprint"